catalog/urls.py
from django.contrib import admin  # type: ignore
from django.urls import path  # type: ignore
from django.conf import settings  # type: ignore
from django.conf.urls.static import static  # type: ignore
from posts.apps import PostsConfig
from catalog.views import HomePageView, ContactsPageView, ProductDetailView, ProductCreateView, ProductUpdateView, \
    ProductDeleteView, VersionUpdateView
from django.views.decorators.cache import cache_page


app_name = PostsConfig.name


urlpatterns = [
    path('', HomePageView.as_view(), name='home_page'),
    path('contacts/', ContactsPageView.as_view()),
    path('products/<int:pk>', cache_page(60)(ProductDetailView.as_view()), name='product_detail'),
    path('create/', ProductCreateView.as_view(), name='create_product'),
    path('update/<int:pk>', ProductUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', ProductDeleteView.as_view(), name='delete'),
    path('version/<uuid:uuid>', VersionUpdateView.as_view(), name='version'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings  # type: ignore
from django.conf.urls.static import static  # type: ignore

urlpatterns = [
  path('admin/', admin.site.urls),
  path('users/', include('users.urls', namespace='users')),
  path('', include('catalog.urls', namespace='catalog')),
  path('post/', include('posts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.contrib import admin  # type: ignore
from django.urls import path  # type: ignore
from django.conf import settings  # type: ignore
from django.conf.urls.static import static  # type: ignore

from posts.apps import PostsConfig
from posts.views import PostCreateView, PostListView, PostDetailView, PostUpdateView, PostDeleteView

app_name = PostsConfig.name

urlpatterns = [
    path('create/', PostCreateView.as_view(), name='create'),
    path('', PostListView.as_view(), name='index'),
    path('view/<slug:slug>/', PostDetailView.as_view(), name='view'),
    path('update/<slug:slug>/', PostUpdateView.as_view(), name='update'),
    path('delete/<slug:slug>/', PostDeleteView.as_view(), name='delete'),
]

users/urls.py
from django.urls import path

from users.apps import UsersConfig
from django.contrib.auth.views import LoginView, LogoutView
from users.forms import UserLoginForm
from users.views import RegisterView, ResetPasswordView

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html', form_class=UserLoginForm), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('reset_password/', ResetPasswordView.as_view(), name='reset_password'),
]

catalog/models.py
from django.db import models
import uuid

from users.models import User

NULLABLE = {'null' : True, 'blank' : True}

class Product(models.Model):
    name = models.CharField(max_length=50, verbose_name='name')
    description = models.TextField(max_length=500, verbose_name='description')
    image_preview = models.ImageField(verbose_name='image', **NULLABLE)
    category = models.CharField(max_length=50, verbose_name='сategory')
    price_per_unit = models.PositiveIntegerField(verbose_name='price')
    creation_date = models.DateField(auto_now_add=True, verbose_name='creation date')
    last_modified_date = models.DateField(auto_now=True, verbose_name='last modified date')
    user_owner = models.ForeignKey(User, verbose_name='user owner', **NULLABLE, on_delete=models.SET_NULL)

    def __str__(self):
        return str(self.name)

    def get_image_url(self):
        if self.image_preview:
            return f"products/{self.image_preview}"
        return ''

    class Meta:
        verbose_name = 'Product'
        verbose_name_plural = 'Products'

        permissions = [
            ("can_cancel_publication", "Can cancel publication"),
            ("can_change_description", "Can change description"),
        ]

class Version(models.Model):
    product = models.ForeignKey(Product, related_name='versions', on_delete=models.CASCADE)
    version_number = models.FloatField(default=1)
    version_name = models.CharField(max_length=50)
    is_active = models.BooleanField(default=False)
    uuid = models.UUIDField(default=uuid.uuid4, unique=True, editable=False)

    class Meta:
        verbose_name = 'Version'
        verbose_name_plural = 'Versions'

        permissions = [
            ("can_cancel_publication", "Can cancel publication"),
        ]


class Category(models.Model):
    name = models.CharField(max_length=50, verbose_name='name')
    description = models.TextField(max_length=250, verbose_name='description')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

class Contact(models.Model):
    name = models.CharField(max_length=100)
    phone = models.CharField(max_length=15, **NULLABLE)
    message = models.TextField()

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Contact'
        verbose_name_plural = 'Contacts'

catalog/forms.py
from django import forms

from catalog.models import Product, Version


class ProductForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

    class Meta:
        model = Product
        fields = ('name', 'description', 'image_preview', 'category', 'price_per_unit')

    def clean_name(self):
        bad_words = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция', 'радар']
        cleaned_data = self.cleaned_data.get('name')

        if cleaned_data:
            for word in bad_words:
                if word in cleaned_data.lower():
                    raise forms.ValidationError('Ваш текст содержит неприемлемые слова.')

        return cleaned_data

    def clean_description(self):
        description = self.cleaned_data.get('description')
        forbidden_words = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция',
                           'радар']
        for word in forbidden_words:
            if word in description.lower():
                raise forms.ValidationError('Ваш текст содержит неприемлемые слова.')

        return description


class VersionForm(forms.ModelForm):
    class Meta:
        model = Version
        fields = ('version_number',
                  'version_name',
                  'is_active')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['is_active'].widget.attrs['class'] = 'form-check-input'


class ProductModeratorForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

    class Meta:
        model = Product
        fields = ('description', 'category')


class VersionForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if field.widget.__class__.__name__ != 'CheckboxInput':
                field.widget.attrs['class'] = 'form-control'

    class Meta:
        model = Version
        fields = ('version_number', 'version_name', 'is_active')


class VersionModeratorForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if field.widget.__class__.__name__ != 'CheckboxInput':
                field.widget.attrs['class'] = 'form-control'

    class Meta:
        model = Version
        fields = ('is_active',)

catalog/views.py
from django.shortcuts import render, get_object_or_404  # type: ignore
from django.core.files.storage import default_storage  # type: ignore
from django.core.paginator import Paginator  # type: ignore
from catalog.forms import ProductForm, ProductModeratorForm, VersionForm, VersionModeratorForm
from catalog.models import Product, Contact, Version
from django.views.generic import DetailView, CreateView, TemplateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView
from django.db.models import Q
from os.path import join
from os.path import basename
from django.core.exceptions import PermissionDenied


class HomePageView(ListView):
    model = Product
    template_name = 'catalog/home.html'
    context_object_name = 'products'
    paginate_by = 12
    ordering = ['id']

    def get_queryset(self):
        # Фильтруем продукты: либо есть активная версия, либо нет версии
        return Product.objects.filter(
            Q(versions__is_active=True) | Q(versions__isnull=True)
        ).order_by('last_modified_date').distinct()

    def get_context_data(self, **kwargs):
        # Добавление активных версий продуктов в контекст
        context = super().get_context_data(**kwargs)
        products = self.get_queryset()  # Получаем список продуктов
        active_versions = {}  # Словарь для хранения активных версий

        # Проходимся по каждому продукту и его связанным версиям
        for product in products:
            active_versions[product.id] = []  # Создаем список для каждого продукта
            versions = product.versions.filter(is_active=True)  # Фильтруем активные версии

            for version in versions:
                active_versions[product.id].append({
                    'version_name': version.version_name,
                    'version_number': version.version_number,
                })

        context['active_versions'] = active_versions  # Добавляем активные версии в контекст

        # Получаем страницу из GET-параметров запроса
        page = self.request.GET.get('page')
        current_page = int(page) if page else 1

        # Определение диапазона страниц для пагинации
        page_numbers_range = 5  # кол-во страниц, отображаемых в "page navigation"
        start_index = int((current_page - 1) / page_numbers_range) * page_numbers_range
        end_index = start_index + page_numbers_range
        paginator = context['paginator']
        if end_index >= paginator.num_pages:
            end_index = paginator.num_pages
        page_range = list(paginator.page_range)[start_index:end_index]
        context['page_range'] = page_range

        return context


class ContactsPageView(TemplateView):
    template_name = 'catalog/contacts.html'

    def post(self, request, *args, **kwargs):
        name = request.POST.get('name')
        phone = request.POST.get('phone')
        message = request.POST.get('message')
        print(f'{name} {phone} {message}')
        Contact.objects.create(name=name, phone=phone, message=message)
        return self.render_to_response(self.get_context_data())


class ProductDetailView(LoginRequiredMixin, DetailView):
    model = Product
    template_name = 'catalog/product_detail.html'
    context_object_name = 'product'
    login_url = "/users/"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        product = self.get_object()
        active_version = product.versions.filter(is_active=True).first()
        context['active_version'] = active_version
        return context


class ProductCreateView(LoginRequiredMixin, CreateView):
    model = Product
    form_class = ProductForm
    template_name = 'catalog/create_product.html'
    login_url = "/users/"
    success_url = reverse_lazy('catalog:home_page')

    def form_valid(self, form):
        form.instance.user_owner = self.request.user
        image_preview = form.cleaned_data['image_preview']
        if image_preview:
            file_name = basename(image_preview.name)
            save_path = join('products', file_name)
            default_storage.save(save_path, image_preview)
            form.instance.image_preview = file_name
            print(save_path, form.instance.image_preview)

        return super().form_valid(form)


class ProductUpdateView(LoginRequiredMixin, UpdateView):
    model = Product
    form_class = ProductForm
    template_name = 'catalog/create_product.html'
    login_url = "/users/"
    success_url = reverse_lazy('catalog:home_page')


    def form_valid(self, form):
        # Получаем предыдущий объект продукта (если это обновление)
        previous_product = self.get_object()

        # Проверяем, существует ли поле 'image_preview' в форме
        if 'image_preview' in form.cleaned_data:
            # Получаем новое изображение из формы
            new_image_preview = form.cleaned_data['image_preview']

            # Проверяем, было ли изображение изменено
            if previous_product and previous_product.image_preview != new_image_preview:
                # Сохраняем новое изображение в подпапке products
                file_name = new_image_preview.name
                save_path = 'products/' + file_name
                default_storage.save(save_path, new_image_preview)
                form.instance.image_preview = file_name

                # Удаляем предыдущее изображение, если оно было изменено
                if previous_product.image_preview:
                    if default_storage.exists(previous_product.image_preview.path):
                        default_storage.delete(previous_product.image_preview.path)

        return super().form_valid(form)

    def get_form_class(self):
        user = self.request.user

        if user == self.object.user_owner:
            return ProductForm

        if user.has_perm("catalog.can_change_description") and user.has_perm("catalog.can_change_category"):
            return ProductModeratorForm
        raise PermissionDenied


class ProductDeleteView(LoginRequiredMixin, DeleteView):
    model = Product
    context_object_name = 'product'
    login_url = "/users/"
    success_url = reverse_lazy('catalog:home_page')

class VersionUpdateView(LoginRequiredMixin, UpdateView):
    model = Version
    form_class = VersionForm
    template_name = 'catalog/create_version.html'
    login_url = "/users/"
    success_url = reverse_lazy('catalog:home_page')

    def get_object(self, queryset=None):
        uuid = self.kwargs.get('uuid')
        return get_object_or_404(Version, uuid=uuid)

    def get_form_class(self):
        user = self.request.user
        version = self.get_object()

        if user == version.product.user_owner:
            return VersionForm

        if user.has_perm("catalog.can_cancel_publication"):
            return VersionModeratorForm
        raise PermissionDenied

catalog/templates/catalog/base.html
{% load static %}
{% load mediapath_tag %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Stepanoff Shop</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="{% static 'css/bootstrap.min.css'%}" rel="stylesheet">
    <link href="{% static 'css/base.css'%}" rel="stylesheet">
    <link href="{% static 'js/base.js'%}" rel="stylesheet">
    {% block css %}
    {% endblock %}
</head>
<body>


<div class="d-flex flex-row align-items-center justify-content-between p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <!-- Логотип слева + кнопки -->
    <a href="/" onclick="window.location.href = '/';">
        <img src="{% mediapath 'company_logo/stepanoff.shop.png' %}" alt="Логотип компании" class="logo_header mr-3">
    </a>
    <a class="p-2 btn btn-outline-primary {% if request.path == '/' %}active{% endif %}"
       style="margin-right: 0px; margin-left: 20px" href="/">Каталог</a>
    <a class="p-2 btn btn-outline-primary {% if request.path == '/post/' %}active{% endif %}" href="/post/"
       style="margin-right: 0px; margin-left: 5px">Блог</a>
    <a class="p-2 btn btn-outline-primary {% if request.path == '/contacts/' %}active{% endif %}" href="/contacts/"
       style="margin-right: 0px; margin-left: 5px">Контакты</a>

    <!-- Поисковая строка по центру -->
    <form class="search-form d-flex justify-content-center align-items-center mx-auto" ; style="width: 500px">
        <input type="text" placeholder="Поиск в разработке..." class="form-control">
        <button type="submit" class="btn btn-outline-primary mx-2">Найти</button>
    </form>

    <!-- Кнопки справа -->
    <nav>
        <a class="p-2 btn btn-outline-primary {% if request.path == '/create/' %}active{% endif %}" href="/create/">+
            Товар</a>
        <a class="p-2 btn btn-outline-primary {% if request.path == '/post/create/' %}active{% endif %}"
           href="/post/create/">+ Пост</a>

        {% if user.is_authenticated %}
        <a class="p-2 btn btn-secondary" href="{% url 'users:logout' %}">Выйти</a>
        {% else %}
        <a class="p-2 btn btn-dark" href="{% url 'users:login' %}">Войти</a>
        <a class="p-2 btn btn-outline-dark" href="{% url 'users:register' %}">Регистрация</a>
        {% endif %}
    </nav>

</div>


<main>
    <div class="container">
        {% block content %}
        {% endblock %}
        <footer class="pt-4 my-md-5 pt-md-5 border-top">
            <div class="row">
                <div class="col-12 col-md">
                    <img src="{% mediapath '/company_logo/stepanoff.shop.png' %}" alt="Логотип компании"
                         class="logo_header mr-3">

                    <small class="d-block mb-3 text-muted">&copy; {% now "Y" %}</small>
                </div>
                <div class="col-6 col-md">
                    <h5>Категории</h5>
                    <ul class="list-unstyled text-small">
                        <li><a class="text-muted" href="#">Рассылки</a></li>
                        <li><a class="text-muted" href="#">Телеграм боты</a></li>
                        <li><a class="text-muted" href="#">Полезные утилиты</a></li>
                        <li><a class="text-muted" href="#">Веб-приложения</a></li>
                        <li><a class="text-muted" href="#">Микросервисы</a></li>
                    </ul>
                </div>
                <div class="col-6 col-md">
                    <h5>Дополнительно</h5>
                    <ul class="list-unstyled text-small">
                        <li><a class="text-muted" href="#">Мы пишем</a></li>
                    </ul>
                </div>
                <div class="col-6 col-md">
                    <h5>О нас</h5>
                    <ul class="list-unstyled text-small">
                        <li><a class="text-muted" href="/contacts/">Контакты</a></li>
                    </ul>
                </div>
            </div>
            <a style="color: inherit; text-decoration: none;" href="https://ru.lovepik.com/images/png-1024220.html">Shopping
                Cart Png vectors by Lovepik.com</a>
        </footer>
    </div>
</main>
</body>
</html>

catalog/templates/catalog/contacts.html
{% extends 'catalog/base.html' %}
{% block content %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Контакты</h1>
</div>

<div class="container">
    <div class="row text-start">
        <div class="col-lg-9 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <table class="table table-striped">
                        <tr>
                            <td class="w-25">Страна</td>
                            <td>USA</td>
                        </tr>
                        <tr>
                            <td class="w-25">ИНН</td>
                            <td>91-1144442</td>
                        </tr>
                        <tr>
                            <td class="w-25">Адрес</td>
                            <td>Redmond,WA,98052-6399</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name">Имя</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя"
                                   required>
                        </div>
                        <div class="mb-3">
                            <label for="phone">Телефон</label>
                            <input type="text" name="phone" class="form-control" id="phone"
                                   placeholder="Контактный телефон" required>
                        </div>
                        <div class="mb-3">
                            <label for="message">Сообщение</label>
                            <textarea type="text" name="message" class="form-control" id="message"
                                      placeholder="У меня такой вопрос" required></textarea>
                        </div>
                        <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

catalog/templates/catalog/create_product.html
{% extends 'catalog/base.html' %}
{% load mediapath_tag %}
{% load static %}

{% block content %}
<form method="post" enctype="multipart/form-data">
    <div class="col-lg-6 mx-auto">
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal">Создайте собственный товар</h4>
            </div>
            <div class="card-body">
                {% csrf_token %}
                {% for field in form %}
                <p>
                    <label for="{{ field.id_for_label }}">{{ field.label }}:</label>
                    {{ field }}
                    {% if field.help_text %}
                    <small class="form-text text-muted">{{ field.help_text }}</small>
                    {% endif %}
                    {% if field.errors %}
                    <div class="invalid-feedback">
                        {% for error in field.errors %}
                        <p>{{ error }}</p>
                        {% endfor %}
                    </div>
                    {% endif %}
                </p>
                {% endfor %}
                <button type="submit" class="btn btn-lg btn-block btn-outline-primary">
                    {% if product %}Обновить{% else %}Сохранить{% endif %}
                </button>
            </div>
        </div>
    </div>
</form>
{% endblock %}

catalog/templates/catalog/create_version.html
{% extends 'catalog/base.html' %}
{% load static %}

{% block content %}
<form method="post" enctype="multipart/form-data">
    <div class="col-lg-6 mx-auto">
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal">Обновите версию</h4>
            </div>
            <div class="card-body">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-lg btn-block btn-outline-primary">
                    Обновить
                </button>
            </div>
        </div>
    </div>
</form>
{% endblock %}

catalog/templates/catalog/home.html
{% extends 'catalog/base.html' %}
{% load mediapath_tag %}
{% load static %}

{% block css %}
<link href="{% static 'css/products-home.css'%}" rel="stylesheet">
{% endblock %}

{% block content %}

<div class="pricing-header text-center" style="padding-top: 20px; padding-bottom: 20px;">
    <img src="{% mediapath 'company_logo/stepanoff.shop.png' %}" alt="Логотип компании" class="logo_title mr-3">
    <p class="lead">Stepanoff Shop — самый лучший интернет магазин в стране</p>
</div>
<div class="container">
    <div class="row">
        {% for product in products %}
        <div class="col-md-3" id="product">
            <div class="product-card">
                <div class="product-image">
                    <img src="{% mediapath product.get_image_url %}" alt="Product Image">
                </div>
                <div class="product-info">

                    <h2 class="product-title"><a style="color: inherit; text-decoration: none;"
                                                 href="/products/{{ product.id }}">
                        {{ product.name }} </a></h2>
                    <p class="product-description">{{ product.description }}</p>
                    <div class="product-price">
                        <span class="product-discount">${{ product.price_per_unit }}</span>
                        <span class="product-old-price">$9999</span>
                    </div>
                    <div>
                        <p></p>
                        {% for version in active_versions|get_item:product.id %}
                        <h6 style="color: #00c906">Активная версия:</h6>
                        <li style="font-size: small">Номер версии: {{ version.version_number }}</li>
                        <li style="font-size: small">Название версии: {{ version.version_name }}</li>
                        {% endfor %}
                    </div>
                    <div class="product-actions">
                        <a type="button" href="/products/{{ product.id }}"
                           class="btn btn-primary">Подробнее</a>
                        <button class="icon-cart-button btn btn-primary">
                        </button>

                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>

    <nav aria-label="Page navigation">
        <ul class="pagination justify-content-center">
            {% if page_range %}
            {% if page_obj.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page=1" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>
            {% endif %}
            {% for num in page_range %}
            <li class="page-item {% if num == page_obj.number %}active{% endif %}">
                <a class="page-link" href="?page={{ num }}">{{ num }}</a>
            </li>
            {% endfor %}
            {% if page_obj.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
            {% endif %}
            {% endif %}
        </ul>
    </nav>


</div>
{% endblock %}

catalog/templates/catalog/product_confirm_delete.html
{% extends 'catalog/base.html' %}
{% load static %}

{% block content %}
<div class="col-lg-6 mx-auto">
    <div class="card mb-4 box-shadow">
        <div class="card-header">
            <h4 class="my-0 font-weight-normal">Хотите удалить товар "{{ product.name }}"?</h4>
        </div>
        <div class="card-body">
            <form method="post">
                {% csrf_token %}
                <p class="mb-3">Подтвердите, чтобы удалить товар. Это действие необратимо.</p>
                <button type="submit" class="btn btn-lg btn-danger mr-2">Подтвердить</button>
                <a href="{% url 'catalog:home_page' %}" class="btn btn-lg btn-secondary">Отмена</a>
            </form>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/product_detail.html
{% extends 'catalog/base.html' %}
{% load mediapath_tag %}
{% load static %}


{% block css %}
<link href="{% static 'css/products-detail.css'%}" rel="stylesheet">
{% endblock %}

{% block content %}
<div class="container">
    <div class="product-details">
        <div class="row">
            <div class="col-md-6">
                <div class="product-image-container">
                    <span class="product-category">Категория: {{ product.category }}</span>
                    <img src="{% mediapath product.get_image_url %}" alt="{{ product.name }}" class="product-image">
                </div>
            </div>
            <div class="col-md-6">
                <h1 class="product-title">{{ product.name }}</h1>
                <p class="product-description">{{ product.description }}</p>
                <p class="product-price"><span class="product-discount">${{ product.price_per_unit }}</span> <span
                        class="product-old-price">$9999</span></p>
                <button class="btn btn-lg btn-block btn-primary w-40">Buy</button>
                {% if perms.catalog.can_change_description and perms.catalog.can_change_category or user == product.user_owner %}
                <a href="/update/{{ product.pk }}" class="btn btn-lg btn-block btn-warning w-40">Edit</a>
                <a href="/version/{{ active_version.uuid }}" class="btn btn-lg btn-block btn-warning w-40">Edit version</a>
                {% endif %}
                <a href="/delete/{{ product.pk }}" class="btn btn-lg btn-block btn-danger w-40">Delete</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}